# Generated by Django 4.1.9 on 2023-12-05 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roomdetail",
            name="name",
        ),
        migrations.AddField(
            model_name="roomdetail",
            name="room",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="base.room"
            ),
        ),
    ]
