# Generated by Django 4.1.9 on 2023-12-05 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_remove_roomdetail_name_roomdetail_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomdetail",
            name="room",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="base.room"
            ),
        ),
    ]
